In [1]:
#Importing models
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Training_data
training_data=pd.read_csv('Train.csv')

In [3]:
import re
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Angshuman\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [5]:
#cleaning text and creating corpus for training data 
corpus = []
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])   #Only alphabets are taken(symbols like coma etc removed)
    review = review.lower() 
    review = review.split()                                        
    ps = PorterStemmer()                                          #Taking the actual/main word (not its any form)
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))] 
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [6]:
for i in range(1000, 2000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
for i in range(2000, 3000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
for i in range(3000, 4000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
for i in range(4000, 5000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [10]:
for i in range(5000, 6000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
for i in range(6000, 7000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [12]:
for i in range(7000, 8000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [13]:
for i in range(8000, 9000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [14]:
for i in range(9000, 10000):
    review = re.sub('[^a-zA-Z]', ' ', training_data['text'][i])
    review = review.lower()                                       
    review = review.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [15]:
#Test Data 
test_data=pd.read_csv('Test.csv')

In [16]:
#cleaning text and creating corpus for test data 
corpus_2 = []
for i in range(0, 1000):
    review_2 = re.sub('[^a-zA-Z]', ' ', test_data['text'][i])
    review_2 = review_2.lower()
    review_2 = review_2.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review_2 = [ps.stem(word) for word in review_2]
    review_2 = ' '.join(review_2)
    corpus_2.append(review_2)

In [17]:
for i in range(1000, 2000):
    review_2 = re.sub('[^a-zA-Z]', ' ', test_data['text'][i])
    review_2 = review_2.lower()
    review_2 = review_2.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review_2 = [ps.stem(word) for word in review_2]
    review_2 = ' '.join(review_2)
    corpus_2.append(review_2)

In [18]:
for i in range(2000, 3000):
    review_2 = re.sub('[^a-zA-Z]', ' ', test_data['text'][i])
    review_2 = review_2.lower()
    review_2 = review_2.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review_2 = [ps.stem(word) for word in review_2]
    review_2 = ' '.join(review_2)
    corpus_2.append(review_2)

In [19]:
for i in range(3000, 4000):
    review_2 = re.sub('[^a-zA-Z]', ' ', test_data['text'][i])
    review_2 = review_2.lower()
    review_2 = review_2.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review_2 = [ps.stem(word) for word in review_2]
    review_2 = ' '.join(review_2)
    corpus_2.append(review_2)

In [20]:
for i in range(4000, 5000):
    review_2 = re.sub('[^a-zA-Z]', ' ', test_data['text'][i])
    review_2 = review_2.lower()
    review_2 = review_2.split()
    ps = PorterStemmer()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review_2 = [ps.stem(word) for word in review_2]
    review_2 = ' '.join(review_2)
    corpus_2.append(review_2)

In [21]:
#Creating Bag of Words for training data
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000,stop_words='english')
X_train = cv.fit_transform(corpus).toarray()
y_train = training_data.iloc[0:10000, 1].values

In [22]:
# Creating Bag of Words for test data
from sklearn.feature_extraction.text import CountVectorizer
X_test = cv.transform(corpus_2).toarray()
y_test = test_data.iloc[0:5000, 1].values

In [23]:
# Applying Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [24]:
# Predicting for test data
y_pred=classifier.predict(X_test)

In [25]:
#Confusion Matrix for Naive Bayes Classifier
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)

In [26]:
print(cm)

[[2095  970]
 [ 400 1535]]


In [27]:
# Finding Accuracy
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.726


In [28]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [29]:
# Applying SVM Model
from sklearn.svm import SVC
classifier_svm=SVC(kernel='linear',random_state=0)
classifier_svm.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [30]:
# Predicting the Test set results
y_pred = classifier_svm.predict(X_test)

In [31]:
#Confusion matrix and accuracy for SVM
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[1911  517]
 [ 584 1988]]


In [32]:
# Finding Accuracy for SVM Model
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.7798


In [35]:
#Creating TF-IDF for training  data
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2000,stop_words='english')
X = tfidf.fit_transform(corpus).toarray()
y = training_data.iloc[0:10000, 1].values

In [36]:
# Applying Naive Bayes Model
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X, y)

GaussianNB()

In [37]:
#Creating TF-IDF for test  data
from sklearn.feature_extraction.text import TfidfVectorizer
#tfidf = TfidfVectorizer(stop_words='english')
X_test_2 = tfidf.transform(corpus_2).toarray()
y_test_2 = test_data.iloc[0:5000, 1].values

In [38]:
# Predicting for test data
y_pred_2=classifier.predict(X_test_2)

In [39]:
#Confusion Matrix for Naive Bayes Classifier ( TF-IDF)
from sklearn.metrics import confusion_matrix
cm_2 = confusion_matrix(y_pred_2,y_test_2)
print(cm_2)

[[1990  525]
 [ 505 1980]]


In [41]:
# Finding Accuracy (TF-IDF by Naive Bayes)
from sklearn import metrics
print(metrics.accuracy_score(y_test_2,y_pred_2))

0.794
